---
title: "AdventOfCode20221202"
output: html_document
date: "2022-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Read in data

```{r}

input_raw <- read_lines("~/Downloads/input20221202.txt")

rps_guide <- data.frame(input = input_raw) %>%
  separate(input,
           sep = " ",
           into = c("opp_play", "response")) %>%
  mutate(
    shape_opp = case_when(opp_play == "A" ~ "Rock",
                             opp_play == "B" ~ "Paper",
                             TRUE ~ "Scissors"),
    shape_resp = case_when(response == "X" ~ "Rock",
                             response == "Y" ~ "Paper",
                             TRUE ~ "Scissors"),
    score_shape = case_when(response == "X" ~ 1,
                             response == "Y" ~ 2,
                             TRUE ~ 3),
    score_outcome = case_when(shape_opp == shape_resp ~ 3,
                              shape_opp == "Rock" & shape_resp == "Paper" ~ 6,
                              shape_opp == "Paper" & shape_resp == "Scissors" ~ 6,
                              shape_opp == "Scissors" & shape_resp == "Rock" ~ 6,
                              TRUE ~ 0),
    total_score = score_shape + score_outcome
  )

glimpse(rps_guide)

```

## Part 1

```{r}

part1 <- rps_guide %>%
  summarize(grand_total_score = sum(total_score)) %>%
  pull(grand_total_score)

part1

```

## Part 2

```{r}

part2 <- rps_guide %>%
  select(1:3) %>%
  rename(outcome = response) %>%
  mutate(
    score_outcome = case_when(
      outcome == "X" ~ 0,
      outcome == "Y" ~ 3,
      TRUE ~ 6),
    score_shape = case_when(
      score_outcome == 3 & shape_opp == "Rock" ~ 1,
      score_outcome == 3 & shape_opp == "Paper" ~ 2,
      score_outcome == 3 & shape_opp == "Scissors" ~ 3,
      score_outcome == 0 & shape_opp == "Rock" ~ 3,
      score_outcome == 0 & shape_opp == "Paper" ~ 1,
      score_outcome == 0 & shape_opp == "Scissors" ~ 2,
      score_outcome == 6 & shape_opp == "Rock" ~ 2,
      score_outcome == 6 & shape_opp == "Paper" ~ 3,
      score_outcome == 6 & shape_opp == "Scissors" ~ 1
    ),
    total_score = score_shape + score_outcome
  ) %>%
  summarize(grand_total_score = sum(total_score)) %>%
  pull(grand_total_score)

part2

```
